# Site settings
name: "Nicolas Gaulard-Querol"
title: Nicolas Gaulard-Querol
email: nicolas.gquerol@gmail.com
description: "ngquerol's personal website"
baseurl: ""
url: "https://ngquerol.github.io"
twitter_username: ngquerol
github_username:  ngquerol

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
