# Site settings
title: ngquerol
author: Nicolas Gaulard-Querol
description: "Nicolas Gaulard-Querol's personal website."
email: nicolas.gquerol@gmail.com
baseurl: ""
timezone: Europe/Paris
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Build settings
markdown: kramdown

# Output
permalink: /blog/:year/:month/:day/:title

# Social media
twitter_username: ngquerol
github_username: ngquerol
linkedin_username: nicolasgaulardquerol

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
