# Site settings
name             : Nicolas Gaulard-Querol
title            : Nicolas Gaulard-Querol
email            : nicolas.gquerol@gmail.com
description      : "ngquerol's personal website"
baseurl          : ""
twitter_username : ngquerol
github_username  : ngquerol

# Build settings
timezone    : Europe/Paris
markdown    : kramdown
highlighter : pygments
permalink   : /blog/:year/:month/:day/:title
